apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adt-auth.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adt-auth.labels" . | nindent 4 }}
type: Opaque
stringData:
    spring.datasource.url: "jdbc:postgresql://alpha-pg.postgres.database.azure.com:5432/hrms_pdn?prepareThreshold=0"
    spring.datasource.username: AlphaPdn
    spring.datasource.password: Alpha@Jun24
    app.jwt.secret: 974CA811EF42C6FFB684734132DBB
  