apiVersion: v1
kind: Service
metadata:
  name: {{ include "adt-payroll.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adt-payroll.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "adt-payroll.selectorLabels" . | nindent 6 }}
