apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adt-gateway.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adt-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
    spring.datasource.url: "jdbc:postgresql://alpha-pg.postgres.database.azure.com:5432/hrms_pdn?prepareThreshold=0"
    spring.datasource.username: AlphaPdn
    spring.datasource.password: alpha@hrms.pdn
  